services:
  html-graph-e2e:
    build:
      dockerfile: ./docker/Dockerfile-e2e
      context: .
      args:
        HOST_USER_ID: ${HOST_USER_ID:-1000}
        HOST_GROUP_ID: ${HOST_GROUP_ID:-1000}
    ports:
      - 0.0.0.0:9323:9323
    volumes:
      - ./:/app
