# syntax=docker/dockerfile:1
FROM ubuntu:24.04  AS image-build

WORKDIR /app

RUN apt-get update
RUN apt-get install sudo zsh nodejs npm -y

RUN npx playwright install-deps

ARG HOST_USER_ID=1000
ARG HOST_GROUP_ID=1000
ARG USER_NAME=user


# create user if not exist
RUN addgroup -S ${HOST_GROUP_ID} && adduser\
 --disabled-password\
 --gecos ""\
 --ingroup "${HOST_GROUP_ID}"\
 --uid "${HOST_USER_ID}"\
 --shell /bin/zsh\
 "${USER_NAME}" || true

# act as non-root user inside container (1000:1000 by default)
USER ${HOST_USER_ID}:${HOST_GROUP_ID}

RUN npx playwright install

# create empty config in order to avoid initial prompt
RUN touch ~/.zshrc

CMD npx playwright test --ui-host=0.0.0.0 --ui-port=39921
