export const forceDirectedDefaults = Object.freeze({
  seed: "HTMLGraph is awesome",
  maxTimeDeltaSec: 1e-2,
  nodeCharge: 1e5,
  nodeMass: 1,
  edgeEquilibriumLength: 300,
  edgeStiffness: 1e3,
  effectiveDistance: 1e3,
  dtSec: 1e-2,
  maxIterations: 1000,
  convergenceDelta: 1,
  maxForce: 1e7,
  nodeForceCoefficient: 1,
  barnesHutAreaRadiusThreshold: 1e-2,
  barnesHutTheta: 1,
});
