name: CI
run-name: Continuous Integration (${{ github.actor }})
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install packages
        run: npm ci
      - name: Run prettier
        run: npm run check-formatting
      - name: Lint code
        run: npm run lint
      - name: Run unit tests
        run: npm run test:ci
      - name: Build production bundle
        run: npm run build
      - name: Build badges
        run: npm install --global jest-coverage-badges && jest-coverage-badges --output ./badges
      - name: Upload badges as artifacts
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: badges/
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
