name: CI
run-name: Continuous Integration (${{ github.actor }})
on:
  push:
    branches: [master]
  pull_request:
jobs:
  ci:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install packages
        run: npm ci
      - name: Run prettier
        run: npm run check-formatting
      - name: Lint code
        run: npm run lint
      - name: Run unit tests
        run: npm run test:ci
      - name: install e2e testing dependencies
        run: npx playwright install --with-deps
      - name: Run e2e tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Build production bundle
        run: npm run build
